### ISSUE TITLE
No such table error 

### ISSUE THREAD

**Issue by AdityaGupta832342** [aadityabaj/python-projects#1]
You need to create a table for new users in your code too. when executed on my system. It gives me no such table: userandpassword error, otherwise it is looking good ...

**Comment by AdityaGupta832342** [comment]
> You need to create a table for new users in your code too. when executed on my system. It gives me no such table: userandpassword error, otherwise it is looking good ...

Well check out this project I made 
----->[Download_Link](https://github.com/Darklight-user/PyMysql-for-CORONA/releases/tag/v1.1)

**Comment by aadityabaj** [comment]
You need to save username and password first

**Comment by aadityabaj** [comment]
Not showing any thing

**Comment by AdityaGupta832342** [comment]
![image](https://user-images.githubusercontent.com/71706433/100743709-b10e1080-3402-11eb-88d1-49767d832bc6.png)
In the image I entered the text into the fields but there is a error showing no such table (I clicked save)
